### ISSUE TITLE
Be more specific with errors

### ISSUE THREAD

**Issue by edmael** [theIYD/jumble-password#2]
Right now if someone enter a wrong date (like "10/12/79") there's a generic "Something is wrong" error.

It would be nice to have a little more details about the error so that the user can correct it.

**Comment by theIYD** [comment]
Correct. The application has not seen updates for days due to my college schedule. Make a pull request to fix the issue.

**Comment by theIYD** [comment]
Issue solved in https://github.com/theIYD/jumble-password/commit/e7e8ddef1b65a5ac693d8a8a5112b264c87f1a9d

Close #2
