### ISSUE TITLE
New logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [theIYD/jumble-password#3]
Hello! I want to contribute on your project with making logo design. What do you think about it?

Best Regards,
Arslan Şahin
Graphics Designer

**Comment by theIYD** [comment]
Hie. 

Go ahead. Contributions are always welcomed. 
Ping me up on Google Hangouts at dargahidrees@gmail.com

**Comment by Arslanshn** [comment]
Hello, I've prepared your logo design, I hope you like it. I apologize for the delay trying to work intensively .. ;-)

https://drive.google.com/folderview?id=1bKVK0s4buLNcIecHeOOjxwrysh0EaGIP

**Comment by theIYD** [comment]
It says "Access Denied"

**Comment by theIYD** [comment]
The design pretty good. Would you mind pinging me on Hangouts for further discussion regarding the design ?

**Comment by theIYD** [comment]
Thank you @Arslanshn for the logo. Closing the issue now ...

**Comment by Arslanshn** [comment]
When will you use the Logotype in Readme?
